# Test configuration
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  liquibase:
    enabled: true
  security:
    enabled: false

# Log levels
#logging:
#  level:
#    org:
#      springframework: INFO
#      testcontainers: INFO
#    com:
#      worldline:
#        taskboard: DEBUG

# Server configuration
server:
  port: 0