# Test configuration
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/taskboard}
    username: postgres
    password: postgres
    liquibase:
      change-log: classpath:db/db.changelog-master.yaml
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
  security:
    enabled: false

# Log levels
#logging:
#  level:
#    org:
#      springframework: INFO
#      testcontainers: INFO
#    com:
#      worldline:
#        taskboard: DEBUG

# Server configuration
server:
  port: 0
